name = "fastconv"
version = "0.1.0"
license = "MIT"
author = "Dominik Gronkiewicz"
maintainer = "gronki@gmail.com"
copyright = "Copyright 2024, Dominik Gronkiewicz"
homepage = "https://github.com/gronki/fastconv"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[library]
source-dir = "src"
[install]
library = true
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

